server:
  port: 8080

logging:
  level:
    root: INFO

datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/?useSSL=false
  username: root
  password:

globalDataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/global?useSSL=false
    username: root
    password: