server:
  port: 8080

logging:
  level:
    root: INFO

datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/
  username: root
  password:

globalDatasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/global
  username: root
  password: