server:
  port: 8080

logging:
  level:
    root: INFO

zookeeper:
  serverLists: localhost:2181
  namespace: test
  baseSleepTimeMilliseconds: 3000
  maxSleepTimeMilliseconds: 3000
  maxRetries: 3
  sessionTimeoutMilliseconds: 3000
  connectionTimeoutMilliseconds: 3000
  digest:
elastic-jobs:
  jobs:
    -
      jobName: test1
      shardingItemParameters: 0=a,1=b,2=c,3=d,4=d,5=d
      cron: 0 */10 * * * ?
      jobClass: ExampleJob
      shardingTotalCount: 5
#    -
#      jobName: test2
#      shardingItemParameters: 0=a,1=b,2=c,3=d,4=d,5=d
#      cron: 0 */1 * * * ?
#      jobClass: ExampleJob
#      shardingTotalCount: 5